learning_rate : 0.0001
max_steps : 50
batch_size : 32
eval_freq : 500
data_dir : ./cifar10/cifar-10-batches-py
--------------Convnet initialized------------
(10000, 3, 32, 32)
-----------------------
test accuracy: 0.09999999999999941
-----------------------
-----------------------
test accuracy: 0.26609999999999956
-----------------------
-----------------------
test accuracy: 0.36900000000000027
-----------------------
-----------------------
test accuracy: 0.39690000000000014
-----------------------
epoch 1 avg accuracy on training data: 0.30012396033269356
Traceback (most recent call last):
  File "train_convnet_pytorch.py", line 216, in <module>
    main()
  File "train_convnet_pytorch.py", line 199, in main
    train()
  File "train_convnet_pytorch.py", line 137, in train
    test_acc, test_loss = calculateTest(X_test, test_labels, 400, cnn, criterion, test_labels_onehot=Y_test)
  File "train_convnet_pytorch.py", line 46, in calculateTest
    test_output = classifier(X_test)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0062/DeepLearningUvA/Assignment 1/code/convnet_pytorch.py", line 128, in forward
    out = layer(out)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 141, in forward
    self.return_indices)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/_jit_internal.py", line 134, in fn
    return if_false(*args, **kwargs)
  File "/home/lgpu0062/.conda/envs/dl/lib/python3.7/site-packages/torch/nn/functional.py", line 487, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 10.92 GiB total capacity; 10.04 GiB already allocated; 1.50 MiB free; 339.13 MiB cached)
srun: error: r31n5: task 0: Exited with exit code 1
